### ISSUE TITLE
ng-if instead of ng-show

### ISSUE THREAD

**Issue by mambax** [fluanceit/angular-dashboard#15]
Why don't you use ng-if in 'dashboard.component.directive.html' to actually remove the not needed elements from the DOM? It would save ressources and prevent some malformats maybe, since there will be less content.

**Comment by sebastienbarbier** [comment]
Oh yeah, awesome idea ! Can you help use and take care of that ? Would be awesome !!!

**Comment by mambax** [comment]
Yes, I can and will.
